### ISSUE TITLE
unresolved dependency: io.nayuki#qrcodegen;1.6: not found

### ISSUE THREAD

**Issue by cyrilfr** [manuelbl/SwissQRBill#30]
Hi,

I cannot install the library in my project from maven. Here is the stack trace:

```
[info] Resolving io.nayuki#qrcodegen;1.6 ...
[warn]  module not found: io.nayuki#qrcodegen;1.6
[warn] ==== local: tried
[warn]   /home/cyril/.ivy2/local/io.nayuki/qrcodegen/1.6/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/nayuki/qrcodegen/1.6/qrcodegen-1.6.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/cyril/.sbt/preloaded/io.nayuki/qrcodegen/1.6/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/cyril/.sbt/preloaded/io/nayuki/qrcodegen/1.6/qrcodegen-1.6.pom
[info] Resolving org.apache.pdfbox#pdfbox;2.0 ...
[warn]  module not found: org.apache.pdfbox#pdfbox;2.0
[warn] ==== local: tried
[warn]   /home/cyril/.ivy2/local/org.apache.pdfbox/pdfbox/2.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/apache/pdfbox/pdfbox/2.0/pdfbox-2.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/cyril/.sbt/preloaded/org.apache.pdfbox/pdfbox/2.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/cyril/.sbt/preloaded/org/apache/pdfbox/pdfbox/2.0/pdfbox-2.0.pom
[info] Resolving jline#jline;2.14.3 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: io.nayuki#qrcodegen;1.6: not found
[warn]  :: org.apache.pdfbox#pdfbox;2.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          io.nayuki:qrcodegen:1.6
[warn]            +- net.codecrete.qrbill:qrbill-generator:2.5.0 (/home/cyril/build.sbt#L60-82)
[warn]            +- vestaweb:vestaweb_2.11:1.0-SNAPSHOT
[warn]          org.apache.pdfbox:pdfbox:2.0
[warn]            +- net.codecrete.qrbill:qrbill-generator:2.5.0 (/home/cyril/build.sbt#L60-82)
[warn]            +- vestaweb:vestaweb_2.11:1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: io.nayuki#qrcodegen;1.6: not found
unresolved dependency: org.apache.pdfbox#pdfbox;2.0: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:320)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:128)
        at sbt.IvySbt.withIvy(Ivy.scala:125)
        at sbt.IvySbt$Module.withModule(Ivy.scala:156)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1555)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1551)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$122.apply(Defaults.scala:1586)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$122.apply(Defaults.scala:1584)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1589)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1583)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1606)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1533)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1485)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: unresolved dependency: io.nayuki#qrcodegen;1.6: not found
[error] unresolved dependency: org.apache.pdfbox#pdfbox;2.0: not found
[error] Total time: 11 s, completed Apr 20, 2021 11:30:18 AM
```

**Comment by manuelbl** [comment]
It looks like an incorrect resolution of version numbers (1.6 instead of 1.6.0 and 2.0 instead of 2.0.0). What build system (incl. version) are you using?

**Comment by cyrilfr** [comment]
I'm using [sbt](https://www.scala-sbt.org/index.html) 0.13 with [Play Framework](https://www.playframework.com/) 2.5.

**Comment by manuelbl** [comment]
After investigating the issue, I still think that *sbt* incorrectly interprets the version range specified for the dependencies *qrcodegen* and *pdfbox*. Anyhow, I've changed the version ranges how I hope they will be more compatible with *sbt*. I didn't test it though.

I've release version 2.5.1. It should appear on Maven Central within a few hours. Let me know if it helps.

**Comment by cyrilfr** [comment]
It works! Thank your very much for your reactivity, I really appreciate :)
