### ISSUE TITLE
Oracle database 12c - Generate PDF

### ISSUE THREAD

**Issue by Knil23** [manuelbl/SwissQRBill#41]
Hello,

we loaded the jar on Oracle DB12c and create our class to generate the qrbill.
If we generate with GraphicsFormat.PNG the QR is generated without problem.
When we try to generate a GraphicsFormat.PDF we get the following error:
`Exception in thread "Root Thread" java.lang.NoClassDefFoundError
	at org.apache.pdfbox.pdfwriter.COSWriter.visitFromStream(COSWriter.java:1404)
	at org.apache.pdfbox.cos.COSStream.accept(COSStream.java:402)
	at org.apache.pdfbox.pdfwriter.COSWriter.doWriteObject(COSWriter.java:599)
	at org.apache.pdfbox.pdfwriter.COSWriter.doWriteBodyCompressed(COSWriter.java:485)
	at org.apache.pdfbox.pdfwriter.COSWriter.visitFromDocument(COSWriter.java:1291)
	at org.apache.pdfbox.cos.COSDocument.accept(COSDocument.java:400)
	at org.apache.pdfbox.pdfwriter.COSWriter.write(COSWriter.java:1569)
	at org.apache.pdfbox.pdfwriter.COSWriter.write(COSWriter.java:1456)
	at org.apache.pdfbox.pdmodel.PDDocument.save(PDDocument.java:1010)
	at org.apache.pdfbox.pdmodel.PDDocument.save(PDDocument.java:930)
	at net.codecrete.qrbill.canvas.PDFCanvas.toByteArray(PDFCanvas.java:275)
	at net.codecrete.qrbill.generator.QRBill.generate(QRBill.java:130)
	at GeneraQRSwissCode2.generateQR(GeneraQRSwissCode2:104)`

I looked up at all dependency and loaded the following jar
`avalon-framework-4.1.5.jar
log4j-1.2.17.jar
logkit-1.0.1.jar
javax_mail.jar
bcmail-jdk15on-1.68.jar
bcpkix-jdk15on-1.68.jar
bcprov-jdk15on-1.68.jar
commons-logging-1.2.jar
fontbox-3.0.0-RC1.jar
pdfbox-3.0.0-RC1.jar
qrcodegen-1.6.0.jar 
qrbill-generator-2.5.3.jar`

The oracle user we use has all java privilage.
We can convert PNG to PDF ourself but the dimension is higher then the one generate as PDF by your class and we have to generate 1000+ invoices.

The oracle DB has a 1.8_121 as JDK, maybe is that the problem .

I hope someone had the same issue.

Thank you in advance.

**Comment by Knil23** [comment]
Hi,
thank you for your replay, the problem were the pdfbox and fontbox version.

Cheers
